### ISSUE TITLE
Ex-developers tracking 

### ISSUE THREAD

**Issue by toxic-environment** [Tox/Tox-Foundation-Discussion#1]
Can you guys @irungentoo explain why you were tracking @Proplex and, moreover, why were you talking about resetting his DigitalOcean account?

https://gist.github.com/urras/ba792274f5aaf662a082

```
+2015-01-14 15:26:57	irungentoo	basically proplex did an email request change on his digital ocean account which means an email containing his ip got sent to david@tox.im which ended up in the catch all email
+2015-01-14 15:27:21	@urras	irungentoo: Any interesting emails?
+2015-01-14 15:27:22	@NikolaiToryzin	He's the only Firefox on Android user running that specific phone model with that specific version of Android.
+2015-01-14 15:27:49	@NikolaiToryzin	So he's totally trackable if you wanted
+2015-01-14 15:28:11	irungentoo	urras, if you want to forcefully gain access to his digital ocean account I can reset his pass
+2015-01-14 15:28:18	@NikolaiToryzin	Why would Firefox on android even show the model.
+2015-01-14 15:28:26	irungentoo	NikolaiToryzin, that's chrome
+2015-01-14 15:28:30	irungentoo	not firefox
+2015-01-14 15:28:31	@NikolaiToryzin	Shit
+2015-01-14 15:28:37	@NikolaiToryzin	I hate ua strings
+2015-01-14 15:28:46	@urras	irungentoo: Nah, I'm just going to text him
+2015-01-14 15:29:07	irungentoo	urras, text him what?
+2015-01-14 15:29:30	@urras	That his user-agent is really unique
+2015-01-14 15:29:42	@urras	Also to change his digitalocean email
+2015-01-14 15:29:51	@NikolaiToryzin	He can't
+2015-01-14 15:29:53	irungentoo	urras, he is changing it
+2015-01-14 15:29:59	@NikolaiToryzin	He's trying
+2015-01-14 15:30:09	@NikolaiToryzin	But they want his personal info
+2015-01-14 15:30:12	@urras	How do you guys know
+2015-01-14 15:30:18	@NikolaiToryzin	Emails.
+2015-01-14 15:30:22	@urras	Ah
+2015-01-14 15:30:45	@urras	>NikolaiToryzin | He's trying  
+2015-01-14 15:30:58	@urras	Just to be clear, "he" is Proplex right?
+2015-01-14 15:31:05	@NikolaiToryzin	Yes.
```

**Comment by suhr** [comment]
Previous thread, as image: http://postimg.org/image/97b7klppl/

**Comment by ameenross** [comment]
"Joined on 20 Jan 2015" does not help your credibility. TBH I see all this shit as FUD from three-letter agencies, even though some concerns may be valid to some extent.

**Comment by ArchangeGabriel** [comment]
The image is missing last post from David Johnson (@dcharles):
```
Ok lets all just take a step back. I think this entire issue is getting out of hand. The recent increase in of drama is starting to scare some people off.

Tox has one end goal, to replace other communication services with a plug and play, secure, and well designed replacement for all platforms. I remember just months ago Tox was on fire, qTox, uTox, and Antox were all rapidly developing into wonderful clients. Then the organization and community started a downfall where constant bickering and arguing was everywhere,

A lot of us are programmers, and most programmers aren't the best with public relations and being the boss, we program and thats that. @irungentoo has been hammered by stupid shit, when his main job is to just program, not be an amazing CEO PR person. @stqism has been put under a shit ton of fire in the PR department when he is working for free and putting his own money in to keep Tox alive. Devs and major contributors like @Proplex (I miss you) have left or taken a break because of arguments and stupid drama.

Now Tox does need a bit of a kick start. If the organization, organized jobs, finances, and code correctly, the project could continue with great success. We need to remember the current group of Tox contributors are not being paid and work for free, so they aren't tolerant to the massive load of bullshit they have to deal with. Now if the big players in Tox will take a step back, restructure the strategy they are implementing right now, and get organized before GSOC, if this is done, the project will have a great boost. Other projects like Hemlis, Skype and Bleep are becoming a lot better as we speak (or Tox ;D ), its up to us to put our differences aside and work together to beat our competitors.

All in all, we need to remember what we are here for, to create a kick ass communication service. Keep on Toxing <3
```

I will post my view when I have time to do so.

**Comment by urras** [comment]
I want to add that the Tox Foundation did not remove the recent issue (1228) intentionally. Apparently, Github staff removed it because of all the accounts that were created on that day. Also, I want to remind everyone to please be civil and to abide by Githubs terms of service. We're open to discussion, not harassment.

**Comment by toxic-environment** [comment]
@ameenross I am a friend of @dfortner and he brought this issue to my attention after being banned of the toxcore repository and name-called by many members. As I don't want to go through that kind of harassment, I created this account for him.

**Comment by toxic-environment** [comment]
**Relevant links**
https://archive.today/JpjxV
http://s21.postimg.org/gzfi3i9sn/1421698175038.png
http://s12.postimg.org/wlj6wj7mz/kqwgsg.png

**Comment by ameenross** [comment]
I have already seen and read those links. And frankly, I've been wasting my time feeding the trolls.

This is FUD and you registered an account just to spread it. It has nothing to do with friendship between you and another github user that felt offended (over what? He was the one harassing others). It's hard to escape the feeling that you are actually a troll.

**Comment by urras** [comment]
@toxic_enviorment think you could link where @dfortner was harassed? I'm not questioning weather he was harassed, but because we take harassment seriously at the project, and I want to make sure that the appropriate action will be taken against them.

**Comment by toxic-environment** [comment]
@dfortner was called a troll by @irungentoo after bringing up the issue shown at http://s21.postimg.org/gzfi3i9sn/1421698175038.png (reposted by the concerned-user afterwards).

As if that wasn't enough, he had his issue defaced by @irungentoo It was edited to say "I want Tox to die." and "I hate how successful Tox is. Please die Tox. Why won't you die??? Why?"
That has nothing to do with what he first said and exposed his image in a bad way, since his account represents his real self.

As if that wasn't enough, he was banned from the repository, so he couldn't even explain himself and confront the harassment, but needed to call me to help him out.

**Comment by zetok** [comment]
@toxic-environment yep, @irungentoo didn't handle well that. Please note that not everyone is perfect in every angle, and everyone makes mistakes. Important part is that lesson was learned, and something like that shouldn't happen in the future.

I gotta say, it's hard to not feel like @dfortner was speaking in troll-ish manner, which seemed to be aimed at hindering people's work, and wasting their time.

Considering that, @irungentoo's reaction isn't really that surprising… Although the way he reacted wasn't the best.

If you keep insisting on making @irungentoo say that he's sorry about what he did… (I guess that's what you're after, if not… why are you so keen on that?) Please answer simple question:

How important is making **troll** like @dfortner happy? (Please note that if one can't communicate properly with other people, instead of helping, actions of that person may have exactly opposite effect.)
Answering question above, please consider that **lesson was learned**, and things like that shouldn't happen in the future.

I guess you don't see that in this light, and thus your reaction…


That being said…

@irungentoo 
>That has nothing to do with what he first said and exposed his image in a bad way, since his account represents his real self.

>As if that wasn't enough, he was banned from the repository, so he couldn't even explain himself and confront the harassment, but needed to call me to help him out.

Please, remove that defaced stuff from @dfortner's comment on irungentoo/toxcore#1226. It's not needed there, ***right***?

**Comment by autious** [comment]
I've been following the issues made in the toxcore repo and i must add that i too have ended up categorizing the entire ordeal as intentional spreading of Fear Uncertainty and Doubt. I don't know if it's intentional or if there are good intentions, but if that's the case it has not come across and everything has been done in a way that is only harmful.

**Comment by urras** [comment]
I'd agree with much of what @zetok is saying, and I would also like to request that the defaced comment on irungentoo/toxcore#1226 be either restored or removed.

**Comment by stqism** [comment]
This drama isn't current.
